name: firebase_course
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Firebase core dependency
  firebase_core: ^3.4.0

  # ✅ Firebase Authentication (login/register)
  firebase_auth: ^5.2.0

  # ✅ Cloud Firestore (database)
  cloud_firestore: ^5.2.0

  # ✅ Firebase Storage (for images/files)
  firebase_storage: ^12.1.0

  # ✅ Firebase Messaging (push notifications)
  firebase_messaging: ^15.0.2

  # ✅ Google Sign-In (optional but useful)
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
