// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFzlPZPMBLNgp_hZXn46fpn5ZqAapYmg',
    appId: '1:61124353809:web:29a34e8d3e6842eb7d36b0',
    messagingSenderId: '61124353809',
    projectId: 'fir-real-90621',
    authDomain: 'fir-real-90621.firebaseapp.com',
    storageBucket: 'fir-real-90621.firebasestorage.app',
    measurementId: 'G-T0T4K7ZZDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEmfmvVUWm1Yf6DJ7760VZWHXRN9S224',
    appId: '1:61124353809:android:72e9509870b63d5a7d36b0',
    messagingSenderId: '61124353809',
    projectId: 'fir-real-90621',
    storageBucket: 'fir-real-90621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF2GPJlrkA8ooA_PEjxbOQzsFHsdkpE4Y',
    appId: '1:61124353809:ios:059a44a779d6a42e7d36b0',
    messagingSenderId: '61124353809',
    projectId: 'fir-real-90621',
    storageBucket: 'fir-real-90621.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );
}
